//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSF.Screenplay.WebApis.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionFormats {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionFormats() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSF.Screenplay.WebApis.Resources.ExceptionFormats", typeof(ExceptionFormats).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The web API request failed: HTTP {0}..
        /// </summary>
        internal static string ApiRequestFailedWithStatusCode {
            get {
                return ResourceManager.GetString("ApiRequestFailedWithStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The web API request timed out after {0}..
        /// </summary>
        internal static string ApiRequestTimedOut {
            get {
                return ResourceManager.GetString("ApiRequestTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may not set the timeout upon a web API request twice..
        /// </summary>
        internal static string CannotSetTimeoutTwice {
            get {
                return ResourceManager.GetString("CannotSetTimeoutTwice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The web API endpoint must specify a non-null HTTP method..
        /// </summary>
        internal static string HttpMethodMustNotBeNull {
            get {
                return ResourceManager.GetString("HttpMethodMustNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The timeout was exceeded whilst reading the HTTP response..
        /// </summary>
        internal static string ReadResponseTimeout {
            get {
                return ResourceManager.GetString("ReadResponseTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The web API request failed for an unexpected reason..
        /// </summary>
        internal static string UnexpectedApiRequestFailure {
            get {
                return ResourceManager.GetString("UnexpectedApiRequestFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The web API endpoint must specify a non-null URI..
        /// </summary>
        internal static string UriMustNotBeNull {
            get {
                return ResourceManager.GetString("UriMustNotBeNull", resourceCulture);
            }
        }
    }
}
