//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSF.Screenplay.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionFormats {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionFormats() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSF.Screenplay.Resources.ExceptionFormats", typeof(ExceptionFormats).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given scenario to begin is already present in the current report builder.  It may not be begun twice..
        /// </summary>
        internal static string DuplicateScenarioInReportBuilder {
            get {
                return ResourceManager.GetString("DuplicateScenarioInReportBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no matching scenario (using the given identity) present in the current report builder..
        /// </summary>
        internal static string NoMatchingScenarioInReportBuilder {
            get {
                return ResourceManager.GetString("NoMatchingScenarioInReportBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whilst building a report about a specific `{0}&apos;, an attempt to get the corresponding `{1}&apos; failed because the {1} was for a different {0}..
        /// </summary>
        internal static string PerformableDoesNotMatchExpectedPerformance {
            get {
                return ResourceManager.GetString("PerformableDoesNotMatchExpectedPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whilst building a report about a specific `{0}&apos;, an attempt to get the corresponding `{1}&apos; failed to find any performances.  This scenario is invalid..
        /// </summary>
        internal static string PerformableWasRequiredInBuilderStack {
            get {
                return ResourceManager.GetString("PerformableWasRequiredInBuilderStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reportable item to write must represent either an actor gaining an ability or a performance..
        /// </summary>
        internal static string ReportableMustBeGainAbilityOrPerformance {
            get {
                return ResourceManager.GetString("ReportableMustBeGainAbilityOrPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scenario has already been finalised; no further actions may be taken against it..
        /// </summary>
        internal static string ScenarioAlreadyFinalised {
            get {
                return ResourceManager.GetString("ScenarioAlreadyFinalised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scenario has not yet been finalised; you must execute &apos;{0}&apos; first to finalise the scenario..
        /// </summary>
        internal static string ScenarioNotFinalisedYet {
            get {
                return ResourceManager.GetString("ScenarioNotFinalisedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The trace event ID must be a positive integer..
        /// </summary>
        internal static string TracableEventIdMustBePositiveInteger {
            get {
                return ResourceManager.GetString("TracableEventIdMustBePositiveInteger", resourceCulture);
            }
        }
    }
}
